config/routes.rb
Rails.application.routes.draw do

#root to: "posts#index"

	resources :todo_lists do
		resources :todo_items do 
			member do
				put :complete	
			end
		end
	end
	root "todo_lists#index"
  resources :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/todo_item.rb
class TodoItem < ActiveRecord::Base
  belongs_to :todo_list
  def completed?
	 !completed_at.blank?
  end
end

app/models/todo_list.rb
class TodoList < ActiveRecord::Base
	has_many :todo_items, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.paginate(:page => params[:page], :per_page => 20)
  end
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
before_action :set_todo_list

def create
@todo_item = @todo_list.todo_items.create(todo_item_params)

	redirect_to @todo_list

end

def destroy
	@todo_item = @todo_list.todo_items.find(params[:id])
@todo_item.destroy
redirect_to @todo_list

end

def complete
	@todo_item = @todo_list.todo_items.find(params[:id])
	if @todo_item.update_attribute(:completed_at, Time.now)
	redirect_to @todo_list, notice: "Todo item completed"
	end
end

private

def set_todo_list
	@todo_list = TodoList.find(params[:todo_list_id])
end

def todo_item_params
	params.require(:todo_item).permit!
end

end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
	before_action :set_todo_list, :except => [:index,:new,:create]
	def new
		@todo_list = TodoList.new
	end

	def create
		@todo_list = TodoList.new(todo_list_params)
		if @todo_list.save
			redirect_to todo_lists_path
		else
			render 'new'
		end
	end

	def show
		
	end

	def index
		@todo_lists = TodoList.all
	end 

	def edit
	end 

	def update
		if @todo_list.update(todo_list_params)
			redirect_to todo_lists_path
		else
			render action: 'edit'
		end
	end

	def destroy
		@todo_list.destroy
		redirect_to root_path
	end 

	def search
	end
	
	private

	def set_todo_list
		@todo_list = TodoList.find(params[:id])
	end

	def todo_list_params
		params.require(:todo_list).permit!
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Todoapp</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %> 
  	<link href='http://fonts.googleapis.com/css?family=Lato:300,400,700' rel='stylesheet' type='text/css'>
	<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>
	<div class="container">
		<%= yield %>
	</div>
</body>
</html>

app/views/posts/_post.html.erb
<div class="post">
  <h2><%= post.title %></h2>
  <p><%= post.body %></p>
</div>

app/views/posts/index.html.erb
<div id="posts">
  <h1>Posts</h1>
  <%= render @posts %>
</div>
<%= will_paginate @posts %>

app/views/posts/index.js.erb
$('#posts').append('<%= escape_javascript render(@posts) %>');
$('.pagination').replaceWith('<%= escape_javascript will_paginate(@posts) %>');

app/views/todo_items/_form.html.erb
<%=form_for([@todo_list, @todo_list.todo_items.build]) do |f| %>

<%= f.text_field :content, placeholder: "New Todo" %>
<%=f.submit%>
<%end%>

app/views/todo_items/_todo_item.html.erb
<div class="row clearfix">
<% if todo_item.completed? %>
<div class="complete">
<%= link_to complete_todo_list_todo_item_path(@todo_list, todo_item.id), method: :put do %>
<i style="opacity: 0.4;" class="fa fa-check"></i>
<% end %>
</div>
<div class="todo_item">
<p style="opacity: 0.4;"><strike><%= todo_item.content %></strike></p>
</div>
<div class="trash">
<%= link_to todo_list_todo_item_path(@todo_list, todo_item.id), method: :delete, data: { confirm: "Are you sure?" } do %>
<i class="fa fa-trash"></i>
<% end %>
</div>
<% else %>
<div class="complete">
<%= link_to complete_todo_list_todo_item_path(@todo_list, todo_item.id), method: :put do %>
<i class="fa fa-check"></i>
<% end %>
</div>
<div class="todo_item">
<p><%= todo_item.content %></p>
</div>
<div class="trash">
<%= link_to todo_list_todo_item_path(@todo_list, todo_item.id), method: :delete, data: { confirm: "Are you sure?" } do %>
<i class="fa fa-trash"></i>
<% end %>
</div>
<% end %>
</div>

app/views/todo_lists/_form.html.erb
<%= form_for @todo_list,:html => { :multipart => true } do |f| %>

 <% if @todo_list.errors.any? %>
<div id="error_explanation">
<h2><%= pluralize(@todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h2>
<ul>
<% @todo_list.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
</div>
<% end %> 

<div class="form-group">
<%= f.label :title %><br>
<%= f.text_field :title %>
</div> 

<div class="form-group">
<%= f.label :description %><br>
<%= f.text_area :description %>
</div>


<div class="actions">
<%= f.submit %>
</div> 

<%end%>

app/views/todo_lists/edit.html.erb
<h1 class= "todo_list_title">Edit TODOLIST</h1>
<div class="form">
<%= render "form" %>
</div>
<div class="links">
<%= link_to "Cancel", todo_lists_path %>
</div>

app/views/todo_lists/index.html.erb
<% @todo_lists.each do |td|%>
<div class="index_row_clearfix">
<h2 class="todo_list_title">
<%= link_to td.title, td%>
</h2>
<p class="todo_list_sub_title">
<%= td.description %>
</p>
</div>

<%end%>


<div class="links">
<%= link_to "New Todo List", new_todo_list_path %>
</div>
<img src="/assets/scor.jpg" alt="my-image" class="circular-image" />
<!-- Twitter -->
<a href="http://twitter.com/home?status=SHAREMESSAGE" title="Share on Twitter" target="_blank" class="btn btn-twitter"><i class="fa fa-twitter"></i> Twitter</a>
 <!-- Facebook -->
<a href="https://www.facebook.com/sharer/sharer.php?u=SHAREMESSAGE" title="Share on Facebook" target="_blank" class="btn btn-facebook"><i class="fa fa-facebook"></i> Facebook</a>
<!-- Google+ -->
<a href="https://plus.google.com/share?url=SHAREMESSAGE" title="Share on Google+" target="_blank" class="btn btn-googleplus"><i class="fa fa-google-plus"></i> Google+</a>
<!-- StumbleUpon -->
<a href="http://www.stumbleupon.com/submit?url=SHAREMESSAGE" title="Share on StumbleUpon" target="_blank" data-placement="top" class="btn btn-stumbleupon"><i class="fa fa-stumbleupon"></i> Stumbleupon</a>
<!-- LinkedIn --> 
<a href="http://www.linkedin.com/shareArticle?mini=true&url=&title=&summary=SHAREMESSAGE" title="Share on LinkedIn" target="_blank" class="btn btn-linkedin"><i class="fa fa-linkedin"></i> LinkedIn</a>

app/views/todo_lists/new.html.erb
<h1 class= "todo_list_title">New TODOLIST</h1>
<div class="form">
<%= render "form" %>
</div>
<div class="links">
<%= link_to "Back", todo_lists_path %>
</div>

app/views/todo_lists/show.html.erb
<p id="notice"><%= notice %></p>

<h2 class="todo_list_title"><%= @todo_list.title %></h2>
<p class="todo_list_sub_title"><%= @todo_list.description %></p>

<div id="todo_items_wrapper">
<%= render @todo_list.todo_items %>
<div id="form">
<%= render "todo_items/form" %>
</div>
</div>

<div class="links">
<%= link_to 'Edit', edit_todo_list_path(@todo_list) %> |
<%= link_to 'Delete', todo_list_path(@todo_list), method: :delete, data: { confirm: "Are you sure?" }
%> |
<%= link_to 'Back', todo_lists_path %>
</div>